version: "3.7"

services:

  bqui:
    image: wordpress:latest
    volumes:
      - /home/ee/docker/bqui/wp:/var/www/html/wp-content
    secrets:
      - wp_db_password
    environment:
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_NAME=wp
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
      - WORDPRESS_DB_HOST=mariadb
    networks:
      - net
      - mariadb
    deploy:
      placement:
          constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:bqui.de"
        - "traefik.docker.network=net"
  mariadb:
    image: mariadb
    volumes:
      - /home/ee/docker/bqui/db:/var/lib/mysql
    secrets:
      - wp_db_password
      - root_db_password
    environment:
      - MYSQL_USER=wp
      - MYSQL_DATABASE=wp
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
    networks:
      - mariadb
    deploy:
      placement:
          constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
secrets:
  wp_db_password:
    external: true
  root_db_password:
    external: true
networks:
  net:
    external: true
  mariadb:
    external: true
